### ISSUE TITLE
[Error: EACCES: permission denied, open '/app/data/secrets.json']

### ISSUE THREAD

**Issue by Vladimi2boom** [AlexSciFier/neonlink#58]
Hello!
first install with docker-compose
root@NUC10-NAS:~/neonlink# docker-compose up
Creating network "neonlink_default" with the default driver
Creating neonlink ... done
Attaching to neonlink
neonlink    | [Error: EACCES: permission denied, open '/app/data/secrets.json'] {
neonlink    |   errno: -13,
neonlink    |   code: 'EACCES',
neonlink    |   syscall: 'open',
neonlink    |   path: '/app/data/secrets.json'
neonlink    | }
neonlink exited with code 1

**Comment by AlexSciFier** [comment]
Hello. It looks like a problem with folder permissions. Try to give the folder the same permissions as the user under which docker is running.

**Comment by Vladimi2boom** [comment]
Hello.
works, thank you

**Comment by AdwaitNPradhan** [comment]
Hi @Vladimi2boom, can you share what you did to make this work? 🤔

**Comment by Vladimi2boom** [comment]
Hi @AdwaitNPradhan,
chmod -R 0755 app/

**Comment by AdwaitNPradhan** [comment]
Thanks for the reply but the thing is, the container does not start so I cant attach to it to run the command. Am I doing it correctly?

**Comment by Vladimi2boom** [comment]
Hi @AdwaitNPradhan,
need stop container then go to /root, find /app, chmod -R 0755 app/

**Comment by TheLux83** [comment]
Hey hey.
I have the same issues, but I'm using docker volumes, so there "should" be no permission issue, if I see that correctly.
```
  neonlink:
    image: alexscifier/neonlink
    container_name: neonlink
    volumes:
      - neonlink_data:/app/data
      - neonlink_background:/app/public/static/media/background
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "80"
```
The volumes were generated, but neonlink complains about access issues as well
```
neonlink  | [Error: EACCES: permission denied, open '/app/data/secrets.json'] {
neonlink  |   errno: -13,
neonlink  |   code: 'EACCES',
neonlink  |   syscall: 'open',
neonlink  |   path: '/app/data/secrets.json'
neonlink  | }
```
I can confirm, that there weren't any files in the volume.
All the other docker container are running fine with the same settings.

**Comment by AlexSciFier** [comment]
I tried to recreate the problem and indeed, if you connect volume, then the problem that you wrote about appears. As a temporary solution, I can offer you to connect the entire /app folder.
```
    volumes:
      - neonlink_data:/app
```

**Comment by AlexSciFier** [comment]
Fixed in 1.4.4

**Comment by kyob** [comment]
I pulled version 1.4.4 and error still exists. Nothing changed.

**Comment by AlexSciFier** [comment]
> I pulled version 1.4.4 and error still exists. Nothing changed.

Can you send docker-compose file and also logs from docker?

**Comment by kyob** [comment]
git log --oneline -n 5
```
3b0d505 (HEAD -> master, origin/master, origin/HEAD) Merge pull request #62 from AlexSciFier/change-default-values
7c53e73 change default columns and max items values
4660abe (tag: v1.4.5) Merge pull request #61 from AlexSciFier/fix-no-login
d181636 change version
a53be5d Merge branch 'master' into fix-no-login
```

docker-compose.yml
```
version: "3.8"

services:
  neonlink:
    image: alexscifier/neonlink
    container_name: neonlink
    volumes:
      - ./data:/app/data
      - ./background:/app/public/static/media/background
    restart: unless-stopped
    ports:
      - "80:3333"
```

docker-compose logs
```
neonlink    | [Error: EACCES: permission denied, open '/app/data/secrets.json'] {
neonlink    |   errno: -13,
neonlink    |   code: 'EACCES',
neonlink    |   syscall: 'open',
neonlink    |   path: '/app/data/secrets.json'
neonlink    | }
```

**Comment by CharlotteCross1998** [comment]
I'm having the same issue, even with the permissions fixed. There are also no files in any of the folders.

## docker-compose:
```
version: "3.8"

services:
  neonlink:
    image: alexscifier/neonlink
    container_name: neonlink
    volumes:
      - /home/charlotte/PodmanContainers/neonlink/data:/app/data
      - /home/charlotte/PodmanContainers/neonlink/background:/app/public/static/media/background
    restart: unless-stopped
    ports:
      - "3333:3333"
```

## ls -Ral
```
~/PodmanContainers/neonlink> ls -Ral 
.:
total 16
drwxr-xr-x  4 1024 users 4096 Aug 24 12:24 .
drwxr-xr-x 23 root root  4096 Aug 24 12:22 ..
drwxr-xr-x  2 1024 users 4096 Aug 24 12:24 background
drwxr-xr-x  2 1024 users 4096 Aug 24 12:30 data

./background:
total 8
drwxr-xr-x 2 1024 users 4096 Aug 24 12:24 .
drwxr-xr-x 4 1024 users 4096 Aug 24 12:24 ..

./data:
total 8
drwxr-xr-x 2 1024 users 4096 Aug 24 12:30 .
drwxr-xr-x 4 1024 users 4096 Aug 24 12:24 ..
```

**Comment by xrfmkrh** [comment]
In my case, I solved this by 'user: uid:gid'

example
---
```version: "3"
services:
  neonlink:
    image: alexscifier/neonlink:1.4.5
    user: uid:gid
    volumes:
      - ./data:/app/data
    restart: unless-stopped

**Comment by AlexSciFier** [comment]
> In my case, I solved this by 'user: uid:gid'

You can also create folder first and then run container.

**Comment by xrfmkrh** [comment]
> You can also create folder first and then run container.

without 'user: uid:gid'? not worked

**Comment by CharlotteCross1998** [comment]
> In my case, I solved this by 'user: uid:gid'
> ## example
> 
> ```
> services:
>   neonlink:
>     image: alexscifier/neonlink:1.4.5
>     user: uid:gid
>     volumes:
>       - ./data:/app/data
>     restart: unless-stopped
> ```

This didn't work for me, still getting the same error.

> > In my case, I solved this by 'user: uid:gid'
> 
> You can also create folder first and then run container.

That's what I did originally, creating the folders then changing the ownership to the docker user, this didn't fix it unfortunately.

**Comment by xrfmkrh** [comment]
@CharlotteCross1998 Did you try 'user: 0:0'?

**Comment by CharlotteCross1998** [comment]
> @CharlotteCross1998 Did you try 'user: 0:0'?

That worked, thanks!
